const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const noop=()=>{},nodes=new Map(),events={};
const ctx=new Proxy({},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});
function node(){const classes=new Set();return {style:{},dataset:{},children:[],handlers:{},attrs:{},classList:{toggle(k,on){if(on)classes.add(k);else classes.delete(k)},add:k=>classes.add(k),remove:k=>classes.delete(k),contains:k=>classes.has(k)},appendChild(x){this.children.push(x)},insertBefore(x){this.children.push(x)},addEventListener(k,f){this.handlers[k]=f},setAttribute(k,v){this.attrs[k]=v},setPointerCapture:noop,getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:1200,height:720})};}
const document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},createElement:node,querySelectorAll:()=>[],addEventListener:noop};
const win={innerWidth:390,innerHeight:844,addEventListener:(k,f)=>(events[k]??=[]).push(f)};
const sandbox={XOLeague:require('../games/xo-football/league.js'),document,window:win,Image:class{},localStorage:{getItem:()=>null},NotebookPaper:{draw:noop},NotebookInk:()=>new Proxy({INK:'#123',RED:'#c00',GRAPHITE:'#333'},{get:(o,k)=>o[k]||noop}),Matter:require('../shared/matter.min.js'),requestAnimationFrame:noop,performance:{now:()=>1},setTimeout:noop,clearTimeout:noop,Math};
vm.createContext(sandbox);const run=s=>vm.runInContext(s,sandbox),html=fs.readFileSync('games/xo-football/play.html','utf8');
run([...html.matchAll(/<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/g)][0][1]);
assert.equal(run('coachMode'),false);assert.equal(run('autoPlayDesign'),false);assert.equal(run('coachPlayReady()'),true,'mobile starts with a designed play even while desktop preference is off');
run('setupPlay()');assert(run('coachPlayReady() && !coachMode'),'mobile designs the next down without switching to Coach Mode');
assert(parseFloat(nodes.get('field-window').style.height)>600,'portrait uses the recovered space for a taller field');
assert.equal(run('phoneGame'),true);assert(nodes.get('wrap').classList.contains('phone-game'));
assert(run('mobileScale')>.5,'phone field is enlarged rather than shrinking the whole notebook');
const canvas=nodes.get('c'),scale=run('mobileScale');canvas.getBoundingClientRect=()=>({left:-145,top:105,width:1200*scale,height:run('fieldViewHeight')*scale});
const point=(id,x,y)=>({pointerId:id,pointerType:'touch',clientX:-145+x*scale,clientY:105+y*scale,preventDefault:noop});
run('introT=9999');canvas.handlers.pointerdown(point(90,330,50));canvas.handlers.pointerup(point(90,330,50));assert.equal(run('state'),'presnap','empty field tap does not accidentally snap on mobile');
const at=run('byName("WR-L").body.position');const sy=run('cam.y');
canvas.handlers.pointerdown(point(1,280+at.x,at.y-sy));assert.equal(run('drawing.name'),'WR-L');
canvas.handlers.pointermove(point(1,280+at.x+15,at.y-sy-65));
canvas.handlers.pointercancel(point(1,280+at.x+15,at.y-sy-65));assert.equal(run('drawing'),null);assert.equal(run('byName("WR-L").route.length'),0,'cancelled touch never keeps a partial route');
run('setMode(false); introT=9999; hike()');assert.equal(run('state'),'live');
assert(nodes.get('side').classList.contains('manual-live'));
const thumb=nodes.get('thumb-pad');thumb.getBoundingClientRect=()=>({left:10,top:600,width:90,height:90});
const thumbTouch=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,preventDefault:noop});
thumb.handlers.pointerdown(thumbTouch(7,78,630));assert(run('keyDir().x>0 && keyDir().y<0'),'thumb direction reaches player steering');
const before=run('byName("QB").body.position.x');for(let i=0;i<8;i++)run('step()');assert(run('byName("QB").body.position.x')>before,'thumb actually moves the QB');
canvas.handlers.pointerdown(point(8,550,240));assert(run('!!aim'));
thumb.handlers.pointerup(thumbTouch(7,78,630));assert(run('!!aim && !ball.flying'),'releasing movement finger does not release pass');
canvas.handlers.pointercancel(point(8,550,240));assert(run('!aim && !ball.flying'),'cancelled aim never throws');
nodes.get('touch-lob').onclick();assert(run('lobHeld()'),'mobile Lob button selects a lob');
canvas.handlers.pointerdown(point(9,550,240));canvas.handlers.pointerup(point(9,550,240));assert(run('!!ball.flying'),'field release throws the pass');
// A mobile catch or handoff must keep moving without a finger held on the thumb pad.
for(const role of ['RB','WR-L']){
 run(`setupPlay(); introT=9999; hike(); giveBall(byName(${JSON.stringify(role)}));`);
 const start=run('ball.carrier.body.position.y');for(let i=0;i<8;i++)run('step()');
 assert(run('ball.carrier.body.position.y')<start-1,role+' automatically runs upfield');
}
assert.equal(nodes.get('touch-note').textContent,'Release to keep running');
thumb.handlers.pointerdown(thumbTouch(10,84,645));assert(run('keyDir(-1).x>0 && keyDir(-1).y===0'),'thumb overrides automatic running');
thumb.handlers.pointerup(thumbTouch(10,84,645));assert(run('keyDir(-1).x===0 && keyDir(-1).y===-1'),'release resumes forward running');
run('setupPlay(); introT=9999; hike()');assert.equal(run('keyDir().y'),0,'QB stays in the pocket without thumb input');const pocketStart=run("byName('QB').body.position.y");for(let i=0;i<8;i++)run('step()');assert(run("byName('QB').body.position.y")>pocketStart+1,'QB drops back automatically without thumb input');
run("setupPlay(); loadPreset('QB sneak'); hike();");const sneakStart=run("byName('QB').body.position.y");for(let i=0;i<8;i++)run('step()');assert(run("byName('QB').body.position.y")<sneakStart-1,'a called QB run follows its route without thumb input');
run("startDrive('pencils'); state='live'; giveBall(byName('CB-L'));");
const returnStart=run('ball.carrier.body.position.y');for(let i=0;i<8;i++)run('step()');assert(run('ball.carrier.body.position.y')>returnStart+1,'interception auto-runs toward the opposite end zone');
win.innerWidth=844;win.innerHeight=390;for(const f of events.resize)f();assert(run('phoneGame'));assert(parseFloat(nodes.get('field-window').style.height)<=334.01,'landscape field fits beside controls');
win.innerWidth=1400;win.innerHeight=900;for(const f of events.resize)f();assert.equal(run('phoneGame'),false);assert.equal(canvas.style.width,'');assert(nodes.get('stage').style.transform.startsWith('scale('),'desktop returns to full desk view');
assert.equal(run('keyDir(-1)'),null,'automatic running stays mobile-only');
assert.equal(run('fieldViewHeight'),720,'desktop restores the original field viewport');
run("startDrive('you')");assert.equal(run('coachPlayReady()'),false,'desktop still starts with automatic design off');
run('setAutoPlayDesign(true); setupPlay()');assert(run('coachPlayReady()'),'desktop auto design remains optional');
run('setAutoPlayDesign(false)');assert.equal(run('coachPlayReady()'),false,'desktop toggle off clears its suggestion');
run('setAutoPlayDesign(true); loadPreset("slants"); setAutoPlayDesign(false)');assert.equal(run('selectedPlay'),'slants','desktop toggle preserves a manually selected play');
console.log('PASS: phone field, touch routes, thumb steering, independent aiming, lob, automatic runs and returns, QB pocket control, orientation, desktop restoration');
