const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map(),noop=()=>{},events={};
const node=()=>({textContent:'',disabled:false,addEventListener:noop,setAttribute:noop,focus:noop,getContext:()=>({})});
const context={document:{body:{classList:{toggle:noop}},querySelector:s=>{if(!nodes.has(s))nodes.set(s,node());return nodes.get(s)},addEventListener:noop},window:{addEventListener:(k,f)=>events[k]=f},NotebookInk:()=>({}),matchMedia:()=>({matches:false}),requestAnimationFrame:noop,HTMLButtonElement:class{},HTMLAnchorElement:class{},Math};
let source=fs.readFileSync('games/tennis/tennis.js','utf8');
source=source.replace('})();',`globalThis.test={reset,point,action,update,togglePause,launch,startCharge,releaseCharge,chooseLob,keys,get:()=>({score,phase,shot,paused,player,playerY,aiY,boost,lobQueued}),set:(x)=>{if(x.score)score=x.score;if(x.player!==undefined)player=target=x.player;if(x.y!==undefined)playerY=targetY=x.y;if(x.aiY!==undefined)aiY=aiDepth=x.aiY;if(x.ball)shot=x.ball;hitStop=0;}};})();`);
vm.runInNewContext(source,context);const t=context.test;
const step=(seconds)=>{for(let i=0;i<seconds*120;i++)t.update(1/120)};
t.reset();t.action();assert.equal(t.get().phase,'play');t.togglePause();const age=t.get().shot.age;step(.2);assert.equal(t.get().shot.age,age);t.togglePause();step(.2);assert(t.get().shot.age>age);
t.reset();t.keys.add('w');step(1);assert(t.get().playerY<.6);t.keys.clear();t.keys.add('s');step(2);assert(t.get().playerY<=1.12);t.keys.clear();
const ball=(kind='normal',z=26)=>({x:.5,y:.82,z,vx:0,vy:.5,vz:0,gravity:300,down:true,kind,age:.3,bounces:0,landingX:.5,landingY:.88});
t.reset();t.action();t.set({player:.5,y:.84,ball:ball()});t.update(.01);assert.equal(t.get().shot.down,false,'automatic volley');
t.reset();t.action();t.chooseLob();t.set({player:.5,y:.84,ball:ball()});t.update(.01);assert.equal(t.get().shot.kind,'lob');assert(t.get().shot.vz>200,'high lob');
t.reset();t.action();t.startCharge();step(.35);t.releaseCharge();t.set({player:.5,y:.84,ball:ball()});t.update(.01);assert.equal(t.get().shot.kind,'hard');
t.reset();t.action();t.set({y:.6,ball:ball('lob',130)});t.update(.01);assert.equal(t.get().shot.down,true,'lob clears volley reach');
t.reset();t.set({score:[6,6]});t.point(0);assert.equal(t.get().phase,'ready');t.point(0);assert.equal(t.get().phase,'over');t.action();assert.equal(t.get().phase,'ready');
t.reset();t.action();t.set({ball:{...ball(),z:.01,vz:-100,bounces:1}});t.update(.01);assert.equal(t.get().score[1],1,'second bounce loses point');
t.reset();t.action();t.startCharge();t.togglePause();t.releaseCharge();assert.equal(t.get().boost,0,'pause clears charged shot');
console.log('PASS: movement bounds, pause, volley, lob, hard shot, lob clearance, win-by-two, reset, second bounce, charge cancellation');
