(() => {
'use strict';
const L=XOLeague,Pen=XOPen,content=document.getElementById('content'),dialog=document.getElementById('player-card');
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=XOBadges.badge,style=t=>`--team:${t.color};--accent:${t.accent}`;
let season=L.load(),selected=season?.team??4,lastFocus,draftPage=0,draftChoice='',recentPick='',draftMessage='',leagueTab='standings',leaderTab='pass',upgradeChoice='';
const phone=matchMedia('(max-width: 650px)');
const attrLabels={speed:'Speed',hands:'Hands',power:'Power',arm:'Arm Strength',accuracy:'Arm Accuracy',leadership:'Leadership',blocking:'Blocking',iq:'IQ'};
const attributes=p=>Object.entries(p.attrs).filter(([k])=>k!=='arm'||p.role==='QB');
const attrDescription=(p,k)=>k==='leadership'?`Boosts both WRs’ Speed, Hands and Power by ${(L.leadershipBoost(p)*100).toFixed(1)}%. Ratings stay capped at 99.`:({speed:'How fast this player gets downfield.',hands:'Catching reach and contested catches.',power:'Blocking weight and breaking tackles.',blocking:'Holding off defenders and opening lanes.',iq:'Reading the ball: up to 5% more catching reach.',arm:'How fast this quarterback throws the ball.',accuracy:'Keeps throws closer to the intended target.'}[k]);
const position=role=>role.startsWith('WR')?'WR':role;
const roleLabel=role=>role==='WR-L'?'WR 1':role==='WR-R'?'WR 2':role;
const option=(id,clubs=L.activeTeams)=>clubs.map(t=>`<option value="${t.id}" ${t.id===id?'selected':''}>${E(t.city)} ${t.name}</option>`).join('');
const stats=p=>({...L.blank(),...season?.stats[p.id]});
const yards=p=>{const s=stats(p);return p.role==='QB'?s.pass+s.rush:s.rush+s.receive+s.returns;};
const tds=p=>{const s=stats(p);return s.td+(p.role==='QB'?s.passTd:0);};
function save(){if(!L.save(season)){document.getElementById('save-note').textContent='Saving unavailable. Keep this page open.';document.getElementById('save-note').classList.add('warning');return false;}return true;}
function weekLabel(w,s=season){const n=L.regularWeeks(s);return w<n?`Week ${w+1} / ${n}`:w===n?'Semifinals':w===n+1?'Notebook Bowl':'Season complete';}
function home(){content.innerHTML=`<div class="game-menu" aria-label="Game modes"><a class="mode-option" href="#quick" aria-label="Quick Play"><span class="menu-lettering lettering-quick" aria-hidden="true"></span><span class="mode-arrow" aria-hidden="true">→</span></a><a class="mode-option" href="#season" aria-label="Season Mode"><span class="menu-lettering lettering-season" aria-hidden="true"></span><span class="mode-arrow" aria-hidden="true">→</span>${season?`<small>${!season.draft.complete?'Continue draft':season.complete?'Season complete':'Continue · '+weekLabel(season.week)}</small>`:''}</a><p class="coming-soon">Keeper League <span>coming soon</span></p></div>`;}
function quickPlay(){const you=L.activeTeams.some(t=>t.id===selected)?selected:4,opp=you===7?0:7;content.innerHTML=`<section class="quick-setup"><h1>Quick Play</h1><div class="match-select"><div><div id="quick-you-emblem">${badge(L.teams[you])}</div><label for="quick-you">Your team</label><select id="quick-you">${option(you)}</select></div><span class="versus">vs.</span><div><div id="quick-opp-emblem">${badge(L.teams[opp])}</div><label for="quick-opp">Opponent</label><select id="quick-opp">${option(opp)}</select></div></div><button class="action" id="quick-start">Hit the field →</button></section>`;
 for(const key of ['you','opp'])document.getElementById('quick-'+key).onchange=e=>{document.getElementById('quick-'+key+'-emblem').innerHTML=badge(L.teams[Number(e.target.value)]);document.getElementById('quick-opp').setCustomValidity('');};
 document.getElementById('quick-start').onclick=()=>{const you=Number(document.getElementById('quick-you').value),opp=Number(document.getElementById('quick-opp').value);if(you===opp){document.getElementById('quick-opp').setCustomValidity('Choose a different opponent.');document.getElementById('quick-opp').reportValidity();return;}location.href=`play.html?you=${you}&opponent=${opp}`;};}
function tiles(picking=true){const clubs=picking?L.activeTeams:L.clubsFor(season);if(!clubs.some(t=>t.id===selected))selected=4;content.innerHTML=`<section class="club-picker"><div class="center-heading"><h1>${picking?'Pick your colors.':'Meet the clubs.'}</h1><p>${clubs.length} clubs. One notebook.</p></div><div class="team-grid" aria-label="Choose your club">${clubs.map(t=>`<button class="team-tile ${t.id===selected?'selected':''}" style="${style(t)}" data-club="${t.id}" aria-pressed="${t.id===selected}">${badge(t)}<strong>${t.name}</strong><span class="selection-check" aria-hidden="true">✓</span></button>`).join('')}</div><div id="club-choice"></div></section>`;clubChoice(picking);}
function clubChoice(picking){const t=L.teams[selected];document.getElementById('club-choice').innerHTML=`<div class="club-choice" style="${style(t)}"><div>${badge(t)}<div><h2>${t.city} ${t.name}</h2><p><span class="swatch" style="color:${t.color}" aria-hidden="true">////</span><span class="swatch" style="color:${t.accent}" aria-hidden="true">////</span> ${t.motto}</p></div></div>${picking?'<button class="action" id="start-season">Draft my team →</button>':`<a href="#roster-${t.id}" class="action">Meet the team →</a>`}</div>`;
 document.getElementById('start-season')?.addEventListener('click',()=>{if(season&&!season.complete){location.hash='season';render();return;}if(season&&!L.archive(season)){document.getElementById('save-note').textContent='Couldn’t archive this season. Free browser storage before starting another.';return;}season=L.create(selected);draftPage=0;draftChoice='';draftMessage='';save();if(location.hash==='#season')render();else location.hash='season';});
 content.querySelectorAll('[data-club]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.club);content.querySelectorAll('[data-club]').forEach(x=>{const on=Number(x.dataset.club)===selected;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',on);});clubChoice(picking);});}
function standings(s=season){return `<div class="ranking header"><span>#</span><span>CLUB</span><span>W</span><span>L</span></div>${L.standings(s).map((t,i)=>`<div class="ranking ${t.id===s.team?'you':''}"><span>${i+1}</span><a href="#roster-${t.id}">${badge(t)}${t.name}${t.id===s.team?'<small>YOU</small>':''}</a><span>${t.w}</span><span>${t.l}</span></div>`).join('')}<details class="small-details"><summary>Tiebreakers & playoffs</summary><p>Top four advance. Ties break on point difference, then points scored.</p></details>`;}
function squadBoard(animate=false){const t=L.teams[season.team],rr=L.rosterFor(season,t.id);const slots=[['WR-L',16,24],['TE',51,13],['WR-R',84,24],['QB',53,53],['RB',26,63]];
return `<div class="squad-board ${animate?'draw-squad':''}" style="${style(t)}" aria-label="Your five starters"><picture class="squad-field-art" aria-hidden="true"><source media="(max-width:650px)" srcset="assets/squad-field-mobile-ink-v1.png"><img src="assets/squad-field-ink-v1.png" alt="" draggable="false"></picture><svg class="formation-lines" viewBox="0 0 800 440" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path class="route-ink" d="M125 80 Q130 43 171 25 M161 27 L175 22 L170 35 M408 41 L453 17 M439 17 L456 14 L449 28 M670 84 L670 43 L715 42 M706 35 L718 42 L705 49 M205 267 Q238 236 294 244 M286 237 L298 246 L283 252"/><path stroke-dasharray="7 8" d="M425 204 Q462 187 516 186 M507 179 L521 185 L508 194"/></g></svg><div class="squad-line" aria-hidden="true">${['LG','C','RG'].map(role=>`<span>${Pen.mark('O',role)}</span>`).join('')}</div>${slots.map(([role,x,y],i)=>{const p=rr.find(p=>p.role===role);return `<button data-player="${p.id}" class="squad-player" style="--x:${x}%;--y:${y}%;--delay:${i*.12}s" aria-label="${roleLabel(role)}: ${E(p.name)}, overall ${p.overall}"><span class="squad-symbol">${Pen.mark('O',p.id,p.number)}</span><small>${position(role)} ${p.overall}</small><strong>${E(p.name)}</strong></button>`;}).join('')}<div class="endzone">${t.name}</div></div>`;}
function draftReveal(){const t=L.teams[season.team];content.innerHTML=`<section class="draft-reveal"><div class="center-heading"><p>Five picks. One squad.</p><h1 tabindex="-1" id="reveal-heading">Meet the ${t.name}.</h1></div>${squadBoard(true)}<div class="reveal-next"><button class="action" id="continue-draft">Let’s play →</button></div></section>`;document.getElementById('continue-draft').onclick=()=>{delete season.draftReveal;save();render();};document.getElementById('reveal-heading').focus();}
function schedule(s=season){const n=L.regularWeeks(s),t=L.teams[s.team];const fixtures=s.schedule.flatMap((week,w)=>week.filter(g=>g.home===t.id||g.away===t.id).map(g=>({g,w})));fixtures.sort((a,b)=>(a.w===s.week?-1:b.w===s.week?1:a.w-b.w));return fixtures.map(({g,w})=>{const o=L.teams[g.home===t.id?g.away:g.home],score=g.score&&(g.home===t.id?g.score:[g.score[1],g.score[0]]);return `<div class="fixture ${w===s.week?'next-fixture':''}"><small>${w<n?'WK '+(w+1):w===n?'SEMI':'BOWL'}</small><span>${g.home===t.id?'vs.':'@'} ${o.name}</span><strong>${score?`${score[0]>score[1]?'W':'L'} ${score[0]}–${score[1]}`:w===s.week?'NEXT':'—'}</strong></div>`;}).join('')+(s.week>=n?`<h3 class="playoff-title">The playoffs</h3>${s.schedule.slice(n).flatMap((week,w)=>week.map(g=>`<div class="fixture"><small>${w?'BOWL':'SEMI'}</small><span>${L.teams[g.home].name} / ${L.teams[g.away].name}</span><strong>${g.score?g.score.join('–'):'—'}</strong></div>`)).join('')}`:'');}
function seasonPage(){if(!season)return tiles();if(season.draftReveal&&season.draft.complete)return draftReveal();if(!season.draft.complete)return draftView();const t=L.teams[season.team],row=L.standings(season).find(r=>r.id===t.id),match=L.current(season),opp=match&&L.teams[match.home===t.id?match.away:match.home],n=L.regularWeeks(season);
const last=season.schedule.flat().filter(g=>g.score&&(g.home===t.id||g.away===t.id)).at(-1),score=last&&(last.home===t.id?last.score:[last.score[1],last.score[0]]),lastText=last?`${score[0]>score[1]?'W':'L'} ${score.join('–')} vs. ${L.teams[last.home===t.id?last.away:last.home].name}`:'Ready for the first snap.';
const next=season.complete?`<p class="tag">Notebook Bowl champions</p>${badge(L.teams[season.champion])}<h2>${L.teams[season.champion].name}</h2>${season.champion===t.id?'<p class="champion-stamp">BOWL CHAMPS ✓</p>':''}<a class="action" href="#new-season">New season →</a>`:match?`<p class="tag">Next matchup · ${match.home===t.id?'home':'away'}</p><div class="next-opponent">${badge(opp)}<div><small>${opp.city}</small><h2>vs. ${opp.name}</h2></div></div><a class="action play-action" href="play.html?season=${encodeURIComponent(season.id)}&match=${match.id}">Play ${season.week<n?'week '+(season.week+1):season.week===n?'semifinal':'the Bowl'} →</a>`:`<p class="tag">Your season is finished</p><h2>${row.w} wins. Next year.</h2><button class="action" id="spectate">Sim ${season.week===n?'semifinals':'the Bowl'} →</button>`;
content.innerHTML=`<div class="season-layout"><section class="squad-main"><div class="squad-heading">${badge(t)}<div><h1>${t.city} ${t.name}</h1><div class="season-record"><strong>${row.w}–${row.l}</strong><span>${lastText}</span><small>${weekLabel(season.week)}</small></div></div></div>${squadBoard()}</section><aside class="next-game">${next}${performanceCard()}${XOReplay.valid(season.highlight)?`<button class="highlight-preview" id="watch-highlight"><span class="tag">Last touchdown · ${season.highlight.yards} yd</span>${XOReplay.poster(season.highlight)}<span>Watch replay →</span></button>`:''}</aside></div><div class="season-extras"><details><summary>Schedule</summary>${schedule()}</details><details><summary>Standings</summary>${standings()}<a href="#leaders">League leaders →</a></details><a href="#roster-${t.id}">Full roster →</a>${L.archives().length?'<a href="#archives">Past seasons →</a>':''}</div>`;
 document.getElementById('spectate')?.addEventListener('click',()=>{L.finishSpectatorWeek(season);save();render();});document.getElementById('watch-highlight')?.addEventListener('click',()=>XOReplay.open(season.highlight));}
function archetype(p){const labels={speed:p.role==='QB'?'Scrambler':'Burner',arm:'Big arm',accuracy:'Pinpoint',leadership:'Team captain',hands:'Safe hands',power:'Power player',blocking:'Road grader',iq:'Play reader'};const k=attributes(p).sort((a,b)=>b[1]-a[1])[0][0];return labels[k];}
function variedOptions(){const options=L.draftOptions(season),chosen=options.length?[options[0]]:[],used=new Set(chosen.map(p=>p.id)),keys=Object.keys(options[0]?.attrs||{}).filter(k=>k!=='arm'||options[0]?.role==='QB');for(const k of keys){const p=[...options].sort((a,b)=>b.attrs[k]-a.attrs[k]||b.overall-a.overall).find(p=>!used.has(p.id));if(p){chosen.push(p);used.add(p.id);}}return [...chosen,...options.filter(p=>!used.has(p.id))];}
function animateDraftEntrance(){
 if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 content.querySelectorAll('.prospect').forEach((card,index)=>{
  card.style.setProperty('--deal-delay',`${index*80}ms`);
  card.querySelectorAll('.prospect-o path').forEach(path=>path.setAttribute('pathLength','1'));
  card.querySelectorAll('.bar svg').forEach(svg=>{
   const fill=document.createElementNS('http://www.w3.org/2000/svg','g');
   fill.classList.add('draft-bar-ink');
   [...svg.querySelectorAll('path')].slice(1).forEach(path=>fill.appendChild(path));
   svg.appendChild(fill);
  });
 });
 content.querySelector('.draft-room').classList.add('draft-enter');
}
function draftView(){const turn=L.draftTurn(season),t=L.teams[season.team],options=variedOptions(),size=phone.matches?1:3,pages=Math.ceil(options.length/size);draftPage=Math.max(0,Math.min(draftPage,pages-1));const shown=options.slice(draftPage*size,(draftPage+1)*size);if(!shown.some(p=>p.id===draftChoice))draftChoice=shown[0]?.id;const own=season.draft.picks.filter(p=>p.team===season.team),choice=shown.find(p=>p.id===draftChoice);
 content.innerHTML=`<section class="draft-room" style="${style(t)}"><div class="draft-heading"><div><h1 tabindex="-1" id="draft-heading">Pick your ${position(turn.role)}.</h1><p>Round ${turn.round+1} of 5 · ${t.name}</p></div><button class="text-button" id="sim-draft">${own.length?'Sim remaining picks':'Sim draft'}</button></div><div class="draft-steps" aria-label="Your five picks">${L.draftRoles.map((role,i)=>{const pick=own.find(p=>p.round===i),p=pick&&season.draft.prospects.find(p=>p.id===pick.playerId);return `<${pick?'button':'span'} ${pick?`data-player="${pick.playerId}" aria-label="${roleLabel(role)}: ${E(p.name)}"`:''} class="draft-slot ${i===turn.round?'on-clock':''} ${pick?'picked':''} ${pick?.playerId===recentPick?'new-pick':''}">${pick?Pen.mark('O',pick.playerId):''}<span>${roleLabel(role)}</span>${pick?'<b aria-hidden="true">✓</b>':''}</${pick?'button':'span'}>`;}).join('')}</div><p class="draft-notice" role="status">${E(draftMessage)||' '}</p><div class="prospect-grid" role="group" aria-label="Available prospects">${shown.map(p=>`<button class="prospect ${p.id===draftChoice?'selected':''}" data-prospect="${p.id}" aria-pressed="${p.id===draftChoice}" aria-label="Select ${E(p.name)}, ${p.overall} overall, ${archetype(p)}"><span class="prospect-head"><span class="prospect-o">${Pen.mark('O',p.id,p.number)}</span><span><strong>${E(p.name)}</strong><small>${p.role}</small></span><span class="prospect-overall" aria-label="Overall ${p.overall}"><b>${p.overall}</b><small>OVR</small></span></span><span class="archetype">${archetype(p)}</span><span class="prospect-attrs">${attributes(p).map(([k,v])=>`<span class="prospect-attr"><span>${attrLabels[k]}</span><span class="bar">${Pen.bar(v,p.id+k)}</span><strong>${v}</strong></span>`).join('')}</span></button>`).join('')}</div><div class="draft-controls"><div class="draft-pages"><button class="text-button" id="prev-prospects" ${draftPage===0?'disabled':''} aria-label="Previous prospects">←</button><span>${phone.matches?draftPage+1: draftPage*size+1}${!phone.matches?'–'+Math.min((draftPage+1)*size,options.length):''} / ${options.length}</span><button class="text-button" id="next-prospects" ${draftPage===pages-1?'disabled':''}>${phone.matches?'Next →':'More prospects →'}</button></div><div class="draft-commit"><button class="text-button" data-scout-choice>Scout</button><button class="action" id="draft-selected">Draft ${E(choice?.name.split(' ')[0])} →</button></div></div></section>`;
 animateDraftEntrance();
 content.querySelectorAll('[data-prospect]').forEach(b=>b.onclick=()=>{draftChoice=b.dataset.prospect;content.querySelectorAll('[data-prospect]').forEach(x=>{const on=x.dataset.prospect===draftChoice;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',on);});const p=options.find(p=>p.id===draftChoice);document.getElementById('draft-selected').textContent='Draft '+p.name.split(' ')[0]+' →';});
 document.getElementById('draft-selected').onclick=()=>pickProspect(draftChoice);content.querySelector('[data-scout-choice]').onclick=()=>player(draftChoice);
 document.getElementById('sim-draft').onclick=()=>{L.simDraft(season);season.draftReveal={player:null};save();draftMessage='';render();};document.getElementById('prev-prospects').onclick=()=>{draftPage--;draftView();};document.getElementById('next-prospects').onclick=()=>{draftPage++;draftView();};}
function pickProspect(id){const p=season?.draft.prospects.find(p=>p.id===id);if(!p||!L.draftPick(season,id))return;if(dialog.open)dialog.close();delete season.draftReveal;if(season.draft.complete)season.draftReveal={player:id};recentPick=id;draftMessage=`✓ ${p.name} is yours.`;draftPage=0;draftChoice='';save();render();document.getElementById('draft-heading')?.focus();}
function rosterRows(players){return players.map(p=>`<button class="roster-row" data-player="${p.id}"><span class="position">${position(p.role)}</span><span><strong>${E(p.name)}</strong><small>#${p.number}</small></span><span>${p.overall}</span><span>${yards(p)}</span><span>${tds(p)}</span></button>`).join('');}
function rosterPage(id){const clubs=L.clubsFor(season);selected=clubs.some(t=>t.id===id)?id:season?.team??4;const t=L.teams[selected],rr=L.rosterFor(season,selected),starters=rr.filter(p=>L.draftRoles.includes(p.role));content.innerHTML=`<div class="section-top"><div><h1>${t.name}</h1><p>Starting five.</p></div><select class="inline-select" id="roster-team" aria-label="Roster team">${option(selected,clubs)}</select></div><div class="roster-list"><div class="roster-row header"><span>POS</span><span>PLAYER</span><span>OVR</span><span>YDS</span><span>TD</span></div>${rosterRows(starters)}</div><details class="support-roster"><summary>Full roster · ${rr.length} players</summary>${rosterRows(rr.filter(p=>!L.draftRoles.includes(p.role)))}</details>`;document.getElementById('roster-team').onchange=e=>location.hash='roster-'+e.target.value;}
function leaders(){const labels={pass:'Passing',rush:'Rushing',receive:'Receiving'},players=L.allPlayers(season).filter(p=>stats(p)[leaderTab]>0).sort((a,b)=>stats(b)[leaderTab]-stats(a)[leaderTab]);return `<div class="category-tabs">${Object.entries(labels).map(([k,v])=>`<button class="text-button ${leaderTab===k?'active':''}" data-leader="${k}" aria-pressed="${leaderTab===k}">${v}</button>`).join('')}</div>${players.length?players.slice(0,10).map((p,i)=>`<button class="leader-row" data-player="${p.id}"><span>${i+1}</span><span><strong>${E(p.name)}</strong><small>${L.teams[p.team].name} · ${position(p.role)}</small></span><span>${stats(p)[leaderTab]} <small>yd</small></span></button>`).join(''):'<p class="empty">No yards on the page. Yet.</p>'}`;}
function leaguePage(){if(!season)return tiles(false);content.innerHTML=`<div class="section-top"><h1>The league</h1><span class="tag">${L.clubsFor(season).length} clubs · ${weekLabel(season.week)}</span></div><div class="category-tabs league-tabs">${['standings','schedule','leaders'].map(k=>`<button class="text-button ${leagueTab===k?'active':''}" data-league="${k}" aria-pressed="${leagueTab===k}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}<a href="#teams">Clubs</a></div><section class="league-content">${leagueTab==='standings'?standings():leagueTab==='schedule'?schedule():leaders()}</section>`;content.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{leagueTab=b.dataset.league;leaguePage();});content.querySelectorAll('[data-leader]').forEach(b=>b.onclick=()=>{leaderTab=b.dataset.leader;leaguePage();});}
function archivedPage(){content.innerHTML=`<h1>Past seasons</h1><div class="archive-list">${L.archives().map(s=>{const t=L.teams[s.team],r=L.standings(s).find(t=>t.id===s.team);return `<details><summary>${t.city} ${t.name} · ${r.w}–${r.l}<span>${L.teams[s.champion].name} won the Bowl</span></summary>${schedule(s)}</details>`;}).join('')||'<p>No finished seasons yet.</p>'}</div>`;}
function playerStats(p,s){if(p.role==='QB')return [['Passing yards',s.pass],['Passing TDs',s.passTd],['Rushing yards',s.rush]];if(p.role.startsWith('WR')||p.role==='TE')return [['Yards',s.receive],['Catches',s.catches],['TDs',s.td]];if(p.role==='RB')return [['Rushing yards',s.rush],['TDs',s.td]];if(['C','LG','RG'].includes(p.role))return [];return [['Return yards',s.returns],['TDs',s.td]];}
function developmentNotes(p){if(p.team===null||!L.draftRoles.includes(p.role))return '';
 const gains=Object.entries(p.upgrades||{}).filter(([,n])=>n>0);
 return `<details class="attribute-help development-notes"><summary>Development${gains.length?' · +'+gains.reduce((n,[,v])=>n+v,0)+' upgraded':''}</summary>${gains.length?`<p>${gains.map(([k,n])=>`${attrLabels[k]} +${n}`).join(' · ')}</p>`:''}<p>100 performance points buys +1 to an attribute you choose. Ratings stop at 99.</p></details>`;
}
function performanceCard(){const points=L.performance(season).points,count=Math.floor(points/L.upgradeCost);
 return `<a class="performance-card" href="#upgrades"><span>Performance points</span><strong>${points}<small>${count?' banked':' / 100'}</small></strong><span>${count?`${count} upgrade${count===1?'':'s'} available →`:'Develop your squad →'}</span></a>`;
}
function upgradesPage(message=''){
 if(!season?.draft.complete)return seasonPage();
 const own=L.rosterFor(season,season.team).filter(p=>L.draftRoles.includes(p.role));
 if(!own.some(p=>p.id===upgradeChoice))upgradeChoice=own[0].id;
 const p=own.find(p=>p.id===upgradeChoice),points=L.performance(season).points,count=Math.floor(points/L.upgradeCost);
 content.innerHTML=`<section class="upgrades-page"><div class="section-top"><h1>Develop your squad.</h1><a href="#season">← My Squad</a></div><div class="points-balance"><strong>${points}</strong><div><span>Performance points</span><small>${count?`${count} upgrade${count===1?'':'s'} available`:`${100-points} to your next upgrade`} · 100 points = +1</small></div></div><div class="upgrade-roster" role="group" aria-label="Choose a player to upgrade">${own.map(player=>`<button data-upgrade-player="${player.id}" class="${player.id===p.id?'selected':''}" aria-pressed="${player.id===p.id}"><small>${roleLabel(player.role)}</small><strong>${E(player.name)}</strong><span>${player.overall} OVR</span></button>`).join('')}</div><h2 class="upgrade-name">${E(p.name)}</h2><div class="upgrade-attributes">${attributes(p).map(([k,v])=>`<div class="upgrade-attribute"><div><span>${attrLabels[k]}</span><strong>${v}<small> / 99</small></strong></div><span class="bar">${Pen.bar(v,p.id+k)}</span><button class="text-button" data-upgrade-attribute="${k}" ${points<100||v>=99?'disabled':''} aria-label="Upgrade ${attrLabels[k]} from ${v} to ${Math.min(99,v+1)} for 100 points">${v>=99?'Max':'+1 · 100 pts'}</button></div>`).join('')}</div><div id="upgrade-confirm"></div><p class="upgrade-result" role="status">${E(message)}</p><details class="points-rules"><summary>How to earn points</summary><p>1 point per 5 yards · 2 per catch · 15 per touchdown · 20 for a win.</p><p>Up to 200 per completed game. Passing and receiving yards count once. Points carry over, and you choose every upgrade.</p></details></section>`;
 content.querySelectorAll('[data-upgrade-player]').forEach(button=>button.onclick=()=>{upgradeChoice=button.dataset.upgradePlayer;upgradesPage();});
 content.querySelectorAll('[data-upgrade-attribute]').forEach(button=>button.onclick=()=>{
  const attribute=button.dataset.upgradeAttribute,from=p.attrs[attribute];
  const confirm=document.getElementById('upgrade-confirm');
  confirm.innerHTML=`<div class="upgrade-confirm"><p>${E(p.name)} · ${attrLabels[attribute]} <strong>${from} → ${from+1}</strong></p><div><button class="text-button" id="cancel-upgrade">Cancel</button><button class="action" id="spend-upgrade">Spend 100 points</button></div></div>`;
  document.getElementById('cancel-upgrade').onclick=()=>{confirm.innerHTML='';button.focus();};
  document.getElementById('spend-upgrade').onclick=()=>{
   const latest=L.load();
   if(!latest||latest.id!==season.id||latest.week!==season.week||(latest.rosterRevision||0)!==(season.rosterRevision||0)){document.querySelector('.upgrade-result').textContent='Your squad changed in another tab. Return to My Squad and try again.';return;}
   const result=L.upgradePlayer(latest,p.id,attribute);
   if(!result.accepted){document.querySelector('.upgrade-result').textContent=result.reason;return;}
   if(!L.save(latest)){document.querySelector('.upgrade-result').textContent='Could not save. Your points have not been spent. Try again.';return;}
   season=latest;upgradesPage(`${p.name} · ${attrLabels[attribute]} ${result.from} → ${result.to}`);
   const status=document.querySelector('.upgrade-result');status.tabIndex=-1;status.focus();
  };
  document.getElementById('spend-upgrade').focus();
 });
}
function player(id){const p=L.allPlayers(season).concat(season?.draft?.prospects||[]).find(p=>p.id===id);if(!p)return;if(!dialog.open)lastFocus=document.activeElement;const prospect=p.team===null,t=L.teams[p.team??season?.team??selected],s=stats(p),peers=prospect?L.draftOptions(season):L.rosterFor(season,p.team).filter(x=>L.draftRoles.includes(p.role)?L.draftRoles.includes(x.role):!L.draftRoles.includes(x.role)),index=peers.findIndex(x=>x.id===id);
 dialog.innerHTML=`<div class="player-inner" style="${style(t)}"><div class="card-top"><span>${prospect?'Draft prospect':t.name}</span><button class="close" aria-label="Close player card">×</button></div><div class="player-heading"><div class="portrait" role="img" aria-label="${position(p.role)}, jersey number ${p.number}">${Pen.mark(prospect||L.roles.indexOf(p.role)<8?'O':'X',p.id,prospect||L.roles.indexOf(p.role)<8?p.number:null,true)}</div><div><h2 id="player-name">${E(p.name)}</h2><p>${position(p.role)}</p></div><div class="overall-rating" aria-label="Overall ${p.overall}"><strong>${p.overall}</strong><span>OVR</span></div></div><div class="player-attributes">${attributes(p).map(([k,v])=>`<div class="attr"><div class="attr-label"><span>${attrLabels[k]}</span><strong>${v}<small> / 99</small></strong></div><div class="bar" role="meter" aria-label="${attrLabels[k]}" aria-valuemin="0" aria-valuemax="99" aria-valuenow="${v}">${Pen.bar(v,p.id+k)}</div></div>`).join('')}</div>${!prospect&&playerStats(p,s).length?`<div class="statline">${playerStats(p,s).map(([label,n])=>`<div><strong>${n}</strong><span>${label}</span></div>`).join('')}</div>`:''}${developmentNotes(p)}<details class="attribute-help"><summary>Scouting notes</summary><p class="quote">“${E(p.quirk)}”</p>${attributes(p).map(([k])=>`<p><strong>${attrLabels[k]}.</strong> ${attrDescription(p,k)}</p>`).join('')}</details>${prospect&&L.draftOptions(season).some(x=>x.id===p.id)?`<button class="action draft-from-card" data-draft="${p.id}">Draft ${E(p.name.split(' ')[0])} →</button>`:''}${peers.length>1&&index>=0?`<div class="player-paging"><button class="text-button" data-peer="${peers[(index+peers.length-1)%peers.length].id}">← Previous</button><span>${index+1} / ${peers.length}</span><button class="text-button" data-peer="${peers[(index+1)%peers.length].id}">Next →</button></div>`:''}</div>`;
 dialog.querySelector('.close').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();dialog.querySelector('[data-draft]')?.addEventListener('click',()=>pickProspect(p.id));dialog.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>{player(b.dataset.peer);dialog.scrollTop=0;dialog.querySelector('.close').focus();});}
dialog.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
content.addEventListener('click',e=>{const b=e.target.closest('[data-player]');if(b)player(b.dataset.player);});
function render(){const page=location.hash.slice(1)||'home';document.querySelector('.notebook').classList.toggle('menu-screen',page==='home');document.body.classList.toggle('draft-screen',page==='season'&&!!season&&!season.draft.complete);document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+((page.startsWith('roster')||page==='upgrades')?'season':['league','leaders','teams'].includes(page)?'league':page);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(page==='quick')quickPlay();else if(page==='season')seasonPage();else if(page==='new-season'){if(season&&!season.complete)seasonPage();else tiles();}else if(page==='teams')tiles(false);else if(page==='upgrades')upgradesPage();else if(page.startsWith('roster'))rosterPage(page.includes('-')?Number(page.split('-')[1]):season?.team??selected);else if(page==='league'||page==='leaders'){if(page==='leaders')leagueTab='leaders';leaguePage();}else if(page==='archives')archivedPage();else if(page==='replay'){seasonPage();if(season?.highlight)XOReplay.open(season.highlight);}else home();}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});window.addEventListener('pageshow',e=>{if(e.persisted){season=L.load();render();}});window.addEventListener('storage',()=>{season=L.load();render();});phone.addEventListener('change',()=>{draftPage=0;if(location.hash==='#season'&&season&&!season.draft.complete)draftView();});render();
})();
