// Replays are a small local recording of the real simulation, not a second game.
window.XOReplay=(()=>{
 const dialog=document.getElementById('replay-dialog');let animation=0,previousFocus;
 function valid(h){return h?.version===1&&Array.isArray(h.frames)&&h.frames.length>1&&h.frames.length<=181&&h.frames.every(f=>Number.isFinite(f.t)&&Array.isArray(f.players)&&f.players.length<=32&&f.players.every(p=>Array.isArray(p)&&p.length===4&&p.every(Number.isFinite))&&Array.isArray(f.ball)&&f.ball.length===3&&f.ball.every(Number.isFinite));}
 function poster(h){if(!valid(h))return '';const f=h.frames[Math.floor(h.frames.length*.65)],top=Math.max(0,Math.min(1120,f.ball[1]-180));const marks=f.players.map(p=>{const color=p[2]===1?'#c0392b':'#1f3d9e';return p[2]===0?`<ellipse cx="${p[0]}" cy="${p[1]}" rx="11" ry="12" stroke="${color}"/>`:`<path d="M${p[0]-10} ${p[1]-10} l20 20 m0 -20 l-20 20" stroke="${color}"/>`;}).join('');return `<svg class="highlight-doodle replay-poster" viewBox="0 ${top} 640 320" aria-hidden="true"><g fill="none" stroke="#233d7833" stroke-width="2">${Array.from({length:11},(_,i)=>`<path d="M0 ${120+i*120} h640"/>`).join('')}<path d="M2 0 v1440 M638 0 v1440"/>${marks}</g><circle cx="${f.ball[0]}" cy="${f.ball[1]}" r="5" fill="#95612c"/><circle cx="320" cy="${top+160}" r="49" fill="#fbf8eee8" stroke="#233d78" stroke-width="2"/><path d="M307 ${top+134} l36 26 l-36 26 Z" fill="none" stroke="#233d78" stroke-width="3"/></svg>`;}
 function open(h){if(!valid(h))return;cancelAnimationFrame(animation);previousFocus=document.activeElement;
 dialog.innerHTML='<div class="replay-inner"><div class="card-top"><h2 id="replay-title">One for the notebook.</h2><button class="close" aria-label="Close replay">×</button></div><canvas class="replay-canvas" width="720" height="630" aria-label="Recorded touchdown replay"></canvas><div class="replay-controls"><button class="text-button" id="replay-play">Pause</button><input type="range" min="0" max="1000" value="0" aria-label="Replay position"><span id="replay-time"></span></div><p class="replay-caption"></p></div>';
 const canvas=dialog.querySelector('canvas'),ctx=canvas.getContext('2d'),scrub=dialog.querySelector('input'),toggle=dialog.querySelector('#replay-play'),time=dialog.querySelector('#replay-time'),frames=h.frames,start=frames[0].t,end=frames.at(-1).t,duration=Math.max(.1,(end-start)/60);let elapsed=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,last=0;
 dialog.querySelector('.replay-caption').textContent=`${h.player} · ${h.yards} yd · ${h.kind==='pick6'?'interception return':'touchdown'}`;
 function draw(){const target=start+elapsed*60;let i=0;while(i<frames.length-2&&frames[i+1].t<target)i++;const a=frames[i],b=frames[i+1],mix=Math.min(1,Math.max(0,(target-a.t)/Math.max(1,b.t-a.t))),lerp=(x,y)=>x+(y-x)*mix,ball=a.ball.map((x,k)=>lerp(x,b.ball[k])),top=Math.max(0,Math.min(810,ball[1]-330));ctx.clearRect(0,0,720,630);ctx.fillStyle='#fbf8ee';ctx.fillRect(0,0,720,630);ctx.save();ctx.translate(40,-top);ctx.strokeStyle='#8393b255';ctx.lineWidth=1;ctx.font='13px Courier New';ctx.fillStyle='#53698f';for(let y=120;y<=1320;y+=120){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(640,y);ctx.stroke();ctx.fillText(String(Math.min((y-120)/12,(1320-y)/12)),10,y-7);}
 for(const y of [0,1320]){ctx.save();ctx.beginPath();ctx.rect(0,y,640,120);ctx.clip();ctx.strokeStyle='#30497644';for(let x=-100;x<760;x+=8){ctx.beginPath();ctx.moveTo(x,y+120);ctx.lineTo(x+105,y);ctx.stroke();}ctx.fillStyle='#233d78';ctx.font='35px Courier New';ctx.textAlign='center';ctx.fillText('ENDZONE',320,y+73);ctx.restore();}
 ctx.strokeStyle='#233d7888';ctx.strokeRect(0,0,640,1440);ctx.beginPath();frames.slice(Math.max(0,i-35),i+1).forEach((f,n)=>{if(n)ctx.lineTo(f.ball[0],f.ball[1]);else ctx.moveTo(f.ball[0],f.ball[1]);});ctx.setLineDash([4,6]);ctx.strokeStyle='#92733366';ctx.stroke();ctx.setLineDash([]);
 a.players.forEach((p,j)=>{const next=b.players[j]||p,x=lerp(p[0],next[0]),y=lerp(p[1],next[1]);ctx.strokeStyle=p[2]===1?'#c0392b':'#1f3d9e';for(let lap=0;lap<3;lap++){ctx.lineWidth=lap?1:1.6;ctx.globalAlpha=lap?.48:.95;const off=Math.sin(j+lap*2)*1.1;ctx.beginPath();if(p[2]===0)ctx.ellipse(x+off,y-off,10+lap*.4,11-lap*.3,.1*lap,0,Math.PI*2);else{ctx.moveTo(x-9+off,y-9);ctx.lineTo(x+9,y+9+off);ctx.moveTo(x+9+off,y-9);ctx.lineTo(x-9,y+9-off);}ctx.stroke();}});ctx.globalAlpha=1;ctx.fillStyle='#8e512b';ctx.beginPath();ctx.ellipse(ball[0],ball[1]-ball[2]*.15,5,8,-.6,0,Math.PI*2);ctx.fill();ctx.restore();if(elapsed>=duration){ctx.fillStyle='#fbf8eee8';ctx.fillRect(140,20,440,56);ctx.fillStyle='#233d78';ctx.font='28px Courier New';ctx.textAlign='center';ctx.fillText('TOUCHDOWN!',360,57);}scrub.value=Math.round(elapsed/duration*1000);time.textContent=elapsed.toFixed(1)+'s';toggle.textContent=playing?'Pause':elapsed>=duration?'Replay':'Play';}
 function tick(now){if(last&&playing){elapsed=Math.min(duration,elapsed+(now-last)/1000);if(elapsed===duration)playing=false;}last=now;draw();if(dialog.open)animation=requestAnimationFrame(tick);}
 toggle.onclick=()=>{if(elapsed>=duration)elapsed=0;playing=!playing;draw();};scrub.oninput=()=>{playing=false;elapsed=Number(scrub.value)/1000*duration;draw();};dialog.querySelector('.close').onclick=()=>dialog.close();dialog.showModal();draw();animation=requestAnimationFrame(tick);
 }
 dialog.addEventListener('close',()=>{cancelAnimationFrame(animation);previousFocus?.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});return {open,valid,poster};
})();
